### PR TITLE
Improved README and added the option to add child elements

### PR DESCRIPTION
**Pull request by chiedojohn**

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Thank you very much, great PR!

**Comment by chiedojohn** [comment]
No prob! Can you update npm?

**Comment by felixrieseberg** [comment]
Done!

**Comment by chiedojohn** [comment]
Thanks man!
If you want to have more control over the dropzone progress bars, checkout the branch I created that I'm using until this PR gets accepted.
https://github.com/enyo/dropzone/pull/961

https://github.com/chiedojohn/React-Dropzone-Component/tree/chiedodropzone

**Pull request merged**
