### PR TITLE
Allow full page dropzones

### PR DESCRIPTION
**Pull request by arjun810**
This seems to work well for us, but I'm not sure if there are scenarios in which this would be problematic. Let me know if you're open to this type of PR, and we can tweak it as needed if so.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Hey! Thank you very much! Code looks good - and as far as I'm concerned, people who are willing to make PRs have a given right to determine the priorities of the module. In this case: Full-page dropzones.

Merged and updated!

**Comment by arjun810** [comment]
Awesome, thanks! Just a bit confused though -- did it actually get merged into 1.3.0?

**Comment by drborges** [comment]
I was about to open a PR for exactly that. Thanks for taking the time @arjun810.

@felixrieseberg are you planning to merge this PR anytime soon?

**Comment by drborges** [comment]
One suggestion, though, it would be nice to have the `props.config.wholePage` documented in the README file.

**Comment by felixrieseberg** [comment]
Sorry for messing this up - I learned an important lesson today (mostly, not to mess with releases after being up for 24 hours). Clearly I released a new version without merging this PR first.

That said, it seems like @drborges PR enables you to select the whole page (or any arbitrary DOM node), so I hope that your use case is solved?

**Comment by felixrieseberg** [comment]
If not, please let me know - I'm super thankful for all PRs :pray: and if this doesn't cut it for you I'll personally make sure that we get something in.

**Comment by arjun810** [comment]
Yup, his PR is better and works great for us. Thanks so much for being so responsive with these!

**Pull request closed without merging**
