### PR TITLE
support for react 0.14.0

### LINKED ISSUE #36: support react 0.14
This report has a commit that adds support for React 0.14:  https://github.com/paulsocal/React-Dropzone-Component

However, they seem to have not sent a pull request.

### PR DESCRIPTION
**Pull request by brianium**
fixes #36

### CODE REVIEW

**Comment by brianium** [comment]
Makes use of `react-dom` and updates examples to work without warnings.

**Comment by felixrieseberg** [comment]
Thanks a lot, great contribution!

**Comment by brianium** [comment]
Great! Thank you. Should this be a minor version bump? Would you mind cutting a new release?

Thanks for the quick review!

**Comment by felixrieseberg** [comment]
Absolutely - the new version should be on npm any second now!

**Pull request merged**
